Add bookings
SweetD0blE/java-shareit pull request #2
Opened 2023-07-08 23:23 UTC by SweetD0blE

2023-07-09 20:23 UTC, sergeymamonov requested changes

2023-07-09 20:23 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +                                                             LocalDateTime t, Pageable page);
Рекомендую даже в таких интерфейсах не давать таких названий аргументам, как t.

2023-07-09 21:10 UTC, SweetD0blE commented
Добрый вечер, спасибо, исправил

2023-07-10 08:36 UTC, sergeymamonov approved these changes

2023-07-10 08:52 UTC, merged