Add item requests
SweetD0blE/java-shareit pull request #3
Opened 2023-07-19 20:12 UTC by SweetD0blE

2023-07-20 21:10 UTC, sergeymamonov requested changes

2023-07-20 21:10 UTC, sergeymamonov commented on src/test/java/ru/practicum/shareit/booking/controller/BookingControllerTest.java
> +    void shouldGetBookingByIdWhenNotExistingUserId_ReturnStatus404() throws Exception {
Схожие тесты можно объединить в один,  превратив его в параметризованный тест. https://reflectoring.io/tutorial-junit5-parameterized-tests/ Но не настаиваю на этом изменении, это как предложение для улучшения

2023-07-21 09:44 UTC, SweetD0blE commented on src/test/java/ru/practicum/shareit/booking/controller/BookingControllerTest.java
> +    void shouldGetBookingByIdWhenNotExistingUserId_ReturnStatus404() throws Exception {
Спасибо за замечание. Сейчас изучаю Docker и хочу успеть до денлайна) Учту

2023-07-21 14:52 UTC, sergeymamonov approved these changes

2023-07-21 14:59 UTC, merged